language: node_js
node_js:
  - "node"
before_install:
  - pip install --user codecov
after_success:
  - npm run coverage
addons:
  apt:
    packages:
      - python-virtualenv
before_script:
  - virtualenv venv
  - source venv/bin/activate
